/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 2;
extern const char* const kSvnInfo[2] = {"https://github.com/zldeng/ActiveMQ_learning.git\n"
"* master\n"
"commit a8b26a9c614b66e95f8c0604225de32bc001b9b6\n"
"Author: dengzhilong <hitdzl@gmail.com>\n"
"Date:   Fri Jun 29 14:45:06 2018 +0800\n"
"\n"
"    Initial commit\n"
"", "https://github.com/zldeng/ActiveMQ_learning.git\n"
"* master\n"
"commit a8b26a9c614b66e95f8c0604225de32bc001b9b6\n"
"Author: dengzhilong <hitdzl@gmail.com>\n"
"Date:   Fri Jun 29 14:45:06 2018 +0800\n"
"\n"
"    Initial commit\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Fri Jun 29 14:46:15 2018";
extern const char kBuilderName[] = "dengzhilong";
extern const char kHostName[] = "LY1F-R010607";
extern const char kCompiler[] = "GCC 4.8.5";
}}
